language: objective-c
osx_image: xcode11.4
podfile: /Users/vladan.randjelovic/Documents/DownloadImage/Podfile
before_install:
- brew tap oclint/formulae
- brew install oclint
script:
  - xcodebuild | tee xcodebuild.log
  - oclint-xcodebuild
  - oclint-json-compilation-database